services:
  db:
    image: postgres:15
    container_name: pontaj_postgres
    environment:
      POSTGRES_USER: pontaj
      POSTGRES_PASSWORD: pontajpass
      POSTGRES_DB: pontajdb
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: pontaj_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://pontaj:pontajpass@db:5432/pontajdb
